### PR TITLE
Fix index.js imports/exports

### PR DESCRIPTION
**Pull request by kaosat-dev**
- [x] fix remaining es6 imports exports

### CODE REVIEW

**Comment by bhouston** [comment]
Why not stick with ES6 and just run this through a pre-processor like Rollup or Babel as we do with ThreeJS?  Seems weird to be going backwards from ES6 to historical methods.

**Comment by kaosat-dev** [comment]
@bhouston that was the case and we will be using es6 for all but modules until the node.js situation is resolved to be honest : put simply , the overhead of building all the time , just for the modules, is just adding way too much complexity (even the best browsers are just *starting* to put it behind a flag at best so modules are in effect not native anywhere)

Don't worry , as soon as Node stuff is finally settled I will personally ensure that we can use es6 modules and make the changes :) sadly last I heard the whole mess with  .mjs etc is not reasuring

**Comment by bhouston** [comment]
okay.  We use ES6 modules all the time in our code base but we transpile for both node and browsers using babel.js.  I just like ES6 modules and some IDEs are now very aware of them.  Their class-specificity allows for better treeshaking as well.

**Comment by bhouston** [comment]
You seem to know your stuff very well, impressive.

**Comment by kaosat-dev** [comment]
sorry I hope I did not come off as too blunt or anything ? (sorry, dead tired, text based communication etc)
I also like es6 modules overall and use them in most of my personal projects, but I have been hoping to use es6 without transpiling for years now, and that damn module situation is still in the way.

Btw I might be extremely biased because I am constantly tweaks all the repos & package for JSCAD for the release , so I might just be feeling the annoyances of transpiling more than would be normal.

**Pull request merged**
